baseURL: http://www.example.com
title: Mujtaba Brohi
theme: hugo-coder
languageCode: en
defaultContentLanguage: en
paginate: 20
pygmentsStyle: bw
pygmentsCodeFences: yes
pygmentsCodeFencesGuessSyntax: yes
enableEmoji: yes
params:
  author: Mujtaba Brohi
  avatarURL: images/avatar.jpg
  colorScheme: auto
  commit: https://github.com/luizdepra/hugo-coder/tree/
  csp:
    childsrc: '''self'''
    connectsrc:
      - '''self'''
      - https://www.google-analytics.com
    fontsrc:
      - '''self'''
      - https://fonts.gstatic.com
      - https://cdn.jsdelivr.net/
    formaction: '''self'''
    framesrc: '''self'''
    imgsrc: '''self'''
    objectsrc: '''none'''
    prefetchsrc: '''self'''
    scriptsrc:
      - '''self'''
      - '''unsafe-inline'''
      - https://www.google-analytics.com
      - https://cdn.jsdelivr.net/
    stylesrc:
      - '''self'''
      - '''unsafe-inline'''
      - https://fonts.googleapis.com/
      - https://cdn.jsdelivr.net/
  customCSS: []
  customJS: []
  customSCSS: []
  dateFormat: January 2, 2006
  description: Mujtaba Brohi's personal website
  hideColorSchemeToggle: no
  info:
    - Graduate Business Analyst
  keywords: blog,developer,personal
  maxSeeAlsoItems: 5
  rtl: no
  since: 2019
  social:
    - icon: fa fa-2x fa-github
      name: Github
      url: https://github.com/mujtababrohi1
      weight: 1
    - icon: fa fa-2x fa-linkedin
      name: LinkedIn
      url: https://au.linkedin.com/in/mujtababrohi
      weight: 4
    - icon: fa fa-2x fa-medium
      name: Medium
      url: https://mujtababrohi.medium.com/
      weight: 5
    - icon: fa fa-2x fa-rss
      name: RSS
      rel: alternate
      type: application/rss+xml
      url: https://myhugosite.com/index.xml
      weight: 6
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
languages:
  en:
    languageName: ':uk:'
    menu:
      main:
        - name: About
          url: about/
          weight: 1
        - name: Blog
          url: posts/
          weight: 2
        - name: Projects
          url: projects/
          weight: 3
        - name: Contact me
          url: contact/
          weight: 5
  pt-br:
    languageName: ':brazil:'
    menu:
      main:
        - name: Sobre
          url: about/
          weight: 1
        - name: Blog
          url: posts/
          weight: 2
        - name: Projetos
          url: projects/
          weight: 3
        - name: Contato
          url: contact/
          weight: 5
    params:
    title: Mujtaba Brohi
